### ISSUE TITLE
How to download a list of accessions?

### ISSUE THREAD

**Issue by phiweger** [pirovc/genome_updater#29]
Say I have a list of accessions that I am interested in (from some article):

```
GCF_003181395.1
GCF_006454475.1
GCF_900447105.1
GCF_004116145.1
```

Can I download them using `genome_updater`? Thank you for your help!

**Comment by pirovc** [comment]
That's a nice functionality to have, but unfortunately not yet implemented. However it's quite easy to get what you want if you generate the assembly_summary for those entries:

```
wget ftp://ftp.ncbi.nih.gov/genomes/ASSEMBLY_REPORTS/assembly_summary_refseq.txt
join <(sort accession_list) <(sort assembly_summary_refseq.txt) -t$'\t' > custom_assembly_summary.txt
genome_updater.sh -e custom_assembly_summary.txt
```
where the `accession_list` is the file with your accessions. I hope that helps!

**Comment by phiweger** [comment]
thx!
