### ISSUE TITLE
xargs fail on OSX

### ISSUE THREAD

**Issue by phiweger** [pirovc/genome_updater#30]
On a Mac:

```bash
# I did
genome_updater.sh -m -t 4 -o bac120 -f genomic.fna.gz -e bac120_assembly_summary_refseq.txt

# Then the connection broke and later I tried the "-i" flag
genome_updater.sh -i -m -t 4 -o bac120 -f genomic.fna.gz -e bac120_assembly_summary_refseq.txt
-------------------------------------------
┌─┐┌─┐┌┐┌┌─┐┌┬┐┌─┐    ┬ ┬┌─┐┌┬┐┌─┐┌┬┐┌─┐┬─┐
│ ┬├┤ ││││ ││││├┤     │ │├─┘ ││├─┤ │ ├┤ ├┬┘
└─┘└─┘┘└┘└─┘┴ ┴└─┘────└─┘┴  ─┴┘┴ ┴ ┴ └─┘┴└─
                                     v0.2.4
-------------------------------------------
Mode: FIX - DOWNLOAD
Working directory: .../bac120/
-------------------------------------------
Checking for missing files in the current version [2021-02-27_15-27-13]
xargs: illegal option -- -
usage: xargs [-0opt] [-E eofstr] [-I replstr [-R replacements] [-S replsize]]
             [-J replstr] [-L number] [-n number [-x]] [-P maxprocs]
             [-s size] [utility [argument ...]]
```

I found [this](https://unix.stackexchange.com/questions/285169/xargs-on-osx-illegal-option) discussion, apparently `xargs` might be used with non-portable options btw7 Linux and OSX?

Thanks for looking into this!

**Comment by pirovc** [comment]
Hi @phiweger 

It seems like the only unsupported `xargs` parameter is the the `--no-run-if-empty`. I have no mac to test it but you could try to remove them with `sed -i 's/--no-run-if-empty//g' genome_updater.sh > genome_updater.sh` and run it again. 

genome_updater was developed and tested with GNU utilities so you may find other issues using the FreeBSD utilities that come with the osx. Let me know if that works or any other problems pops up.

**Comment by phiweger** [comment]
I solved it using the `brew` package manager to install a GNU `xargs`:

```bash
brew install findutils
brew info findutils
which xargs
# /usr/bin/xargs
PATH="/usr/local/opt/findutils/libexec/gnubin:$PATH"
which xargs
# /usr/local/opt/findutils/libexec/gnubin/xargs
genome_updater.sh -i -m -t 4 -o bac120 -f genomic.fna.gz -e bac120_assembly_summary_refseq.txt
```
