### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by sashiz** [pirovc/genome_updater#33]
Hi there,

When I tried to implement the software, I run into a problem saying "./genome_updater.sh: Permission denied". Can I ask what caused this issue and how can I solve it? Thank you.

**Comment by pirovc** [comment]
Hi @sashiz 

Before running a script you have to allow it be executable e.g. `chmod +x genome_updater.sh`

**Comment by sashiz** [comment]
> Hi @sashiz
> 
> Before running a script you have to allow it be executable e.g. `chmod +x genome_updater.sh`

Thanks for your reply. This permission denied issue was solved, but a new issue was raised:
_./genome_updater.sh -d "genbank,refseq" -g "species:562" -f "genomic.fna.gz" -o "all_ecoli" -t 12 -b v1
readlink: illegal option -- m
usage: readlink [-n] [file ...]_

I am using an example you provided, can you please comment how can I solve this problem? Thank you so much.

**Comment by pirovc** [comment]
Which OS are you using? Could you please post the output of `./genome_updater.sh -D`?

**Comment by sashiz** [comment]
> Which OS are you using? Could you please post the output of `./genome_updater.sh -D`?

I am using MacOS 10.15.7, and the output of it is as follows:
_========================================================
genome_updater version 0.2.5
========================================================
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)
Copyright (C) 2007 Free Software Foundation, Inc.
========================================================
LANG="en_AU.UTF-8"
LC_COLLATE="en_AU.UTF-8"
LC_CTYPE="en_AU.UTF-8"
LC_MESSAGES="en_AU.UTF-8"
LC_MONETARY="en_AU.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_AU.UTF-8"
LC_ALL=
========================================================
awk => /usr/bin/awk
========================================================
awk version 20070501
========================================================
bc => /usr/bin/bc
========================================================
bc 1.06
Copyright 1991-1994, 1997, 1998, 2000 Free Software Foundation, Inc.
========================================================
find => /usr/bin/find
========================================================
/usr/bin/find: illegal option -- -
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]_

Again, thank you so much for your response.

**Comment by sashiz** [comment]
> Which OS are you using? Could you please post the output of `./genome_updater.sh -D`?

I am using MacOS 10.15.7, and the output is as follows:
`mac3145:genome_updater zhang.z$ ./genome_updater.sh -D
========================================================
genome_updater version 0.2.5
========================================================
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)
Copyright (C) 2007 Free Software Foundation, Inc.
========================================================
LANG="en_AU.UTF-8"
LC_COLLATE="en_AU.UTF-8"
LC_CTYPE="en_AU.UTF-8"
LC_MESSAGES="en_AU.UTF-8"
LC_MONETARY="en_AU.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_AU.UTF-8"
LC_ALL=
========================================================
awk => /usr/bin/awk
========================================================
awk version 20070501
========================================================
bc => /usr/bin/bc
========================================================
bc 1.06
Copyright 1991-1994, 1997, 1998, 2000 Free Software Foundation, Inc.
========================================================
find => /usr/bin/find
========================================================
/usr/bin/find: illegal option -- -
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
`

Thank you so much for your response.

**Comment by sashiz** [comment]
> > Which OS are you using? Could you please post the output of `./genome_updater.sh -D`?
> 
> # I am using MacOS 10.15.7, and the output is as follows:
> `mac3145:genome_updater zhang.z$ ./genome_updater.sh -D
> # genome_updater version 0.2.5
> # GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)
> Copyright (C) 2007 Free Software Foundation, Inc.
> # LANG="en_AU.UTF-8"
> LC_COLLATE="en_AU.UTF-8"
> LC_CTYPE="en_AU.UTF-8"
> LC_MESSAGES="en_AU.UTF-8"
> LC_MONETARY="en_AU.UTF-8"
> LC_NUMERIC="en_US.UTF-8"
> LC_TIME="en_AU.UTF-8"
> LC_ALL=
> # awk => /usr/bin/awk
> # awk version 20070501
> # bc => /usr/bin/bc
> # bc 1.06
> Copyright 1991-1994, 1997, 1998, 2000 Free Software Foundation, Inc.
> # find => /usr/bin/find
> /usr/bin/find: illegal option -- -
> usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
> find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
> `
> 
> Thank you so much for your response.

I tried to edit it to a more readable style but failed, sorry if it bothers you.

**Comment by pirovc** [comment]
The bash utilities on MacOS can have some crucial differences from the GNU versions used/tested with genome_updater. Unfortunately there's no direct support to MacOS but everything should work fine if you install coreutils and gawk packages in your environment. Another used had a similar issues #30 you can take a look.

**Comment by sashiz** [comment]
> gawk

Thank you very much :D. After installing coreutils and followed by [this ](http://biercoff.com/readlink-f-unrecognized-option-problem-solution-on-mac/), it stops reporting that error. But somehow the actual fasta files cannot be downloaded. Here is an example:

./genome_updater.sh -d "refseq" -g "archaea,bacteria" -c "all" -l "Complete Genome" -f "genomic.fna.gz" -o "arc_bac_refseq_cg" -t 12 -u -m
-------------------------------------------
┌─┐┌─┐┌┐┌┌─┐┌┬┐┌─┐    ┬ ┬┌─┐┌┬┐┌─┐┌┬┐┌─┐┬─┐
│ ┬├┤ ││││ ││││├┤     │ │├─┘ ││├─┤ │ ├┤ ├┬┘
└─┘└─┘┘└┘└─┘┴ ┴└─┘────└─┘┴  ─┴┘┴ ┴ ┴ └─┘┴└─
                                     v0.2.5 
-------------------------------------------
Mode: NEW - DOWNLOAD
Working directory: /Users/zhang.z/genome_updater/arc_bac_refseq_cg/
-------------------------------------------
Downloading assembly summary [2021-07-08_19-49-25]
 -  entries available
 - 0 entries removed with filters: RefSeq category=all, Assembly level=Complete Genome, Version status=latest, valid URLs
 -  entries to be downloaded
ln: illegal option -- r
usage: ln [-Ffhinsv] source_file [target_file]
       ln [-Ffhinsv] source_file ... target_dir
       link source_file target_file

**Comment by pirovc** [comment]
The error is still the same, the `ln` version in your MacOS is not compatible.

**Comment by sashiz** [comment]
> The error is still the same, the `ln` version in your MacOS is not compatible.

Thank you so much for your time... I don't quite know the GNU thing, do you expect this error will disappear if I changed to windows?

**Comment by pirovc** [comment]
In Windows it will only work using the WSL. genome_updater works natively on most linux distributions.

**Comment by sashiz** [comment]
> In Windows it will only work using the WSL. genome_updater works natively on most linux distributions.

OK... Is there any way to solve the ln error? Really appreciate it.

**Comment by pirovc** [comment]
I do not have a MacOS available to help you, sorry.

**Comment by sashiz** [comment]
> I do not have a MacOS available to help you, sorry.

Thank you so much. Have a great day.
