### ISSUE TITLE
ftp.ncbi.nlm.nih.gov/genomes/{genbank, refseq} URL changed

### ISSUE THREAD

**Issue by shenwei356** [pirovc/genome_updater#36]
Sadly, it's https://ftp.ncbi.nlm.nih.gov/genomes/genbank_old/ now, there's no https://ftp.ncbi.nlm.nih.gov/genomes/genbank/ anymore.

**Comment by pirovc** [comment]
thanks for the heads up, I will adapt the code but it seems like both are still online. Do you have an official note or source from NCBI regarding this change?

**Comment by shenwei356** [comment]
No, a few hours ago, I failed to run, it reports 0 genomes to download. So I checked the URL and found this.

**Comment by shenwei356** [comment]
Here're the [release blog](https://ncbiinsights.ncbi.nlm.nih.gov/2021/11/15/genbank-release-246/) and [note](https://ftp.ncbi.nih.gov/genbank/gbrel.txt) around the date of the changes, but no words mentioned the changes.

**Comment by pirovc** [comment]
That's odd, such a sudden and big change without any information. I'll wait a bit more too make sure it's persistent. In the mean time if you need to use genome_updater, just change those lines replacing `/${d}/` with `/${d}_old/`

https://github.com/pirovc/genome_updater/blob/67a320e333bdae6310e4612752ea6271ef3b7a90/genome_updater.sh#L101

https://github.com/pirovc/genome_updater/blob/67a320e333bdae6310e4612752ea6271ef3b7a90/genome_updater.sh#L110

**Comment by shenwei356** [comment]
Thank you! genome_updater.sh is well written, I've edited the script and it had been working for a while.

**Comment by shenwei356** [comment]
I've @ NCBI on Twitter, hope gets some feedback. https://twitter.com/shenwei356/status/1467809368234426368

**Comment by shenwei356** [comment]
They are back!!!

**Comment by pirovc** [comment]
Gonna leave it open for now until we figure it out what is going on

**Comment by shenwei356** [comment]
Seems OK now.
