### ISSUE TITLE
combine refseq categories to give 1 per species with priority for best assembly

### ISSUE THREAD

**Issue by rjsorr** [pirovc/genome_updater#38]
Hi, 
I want to combine the refseq categories to make a bigger database for groups with few complete genomes. So optimally I would like to do -g "taxids:2759" -d "refseq" -l "Complete Genome,Chromosome,Scaffold,Contig" but also have -j "species:1" taking priority for the most complete assembly. However, at present I cannot see how to do this? if I run this command I get "Assembly level - Complete Genome,Chromosome,Scaffold,Contig - not valid" and likewise if I seperate the assembly level I get species duplicates. I was hoping scaffold, for example, would pull out scaffold and above (so Genome,Chromosome,Scaffold), but it pulls out just scaffold. As such, if I download seperate assemblies and merge I get species duplicates. Any way around this or anything for a future update.  

Alternatively, If I run: 
genome_updater.sh -g "taxids:2759" -d "refseq" -l "Complete Genome" -f "genomic.fna.gz,assembly_report.txt" -o "euk_refseq" -b "21_12_2021" -j "species:1" -a -m -u -r -p -t 8 &

and then later:
genome_updater.sh -d "refseq" -g "taxids:2759" -c "all" -l "Scaffolds" -f "genomic.fna.gz" -o "euk_refseq" -b "22_12_2021" -k -j "species:1" -t 8

can I get it to filter on the species? it just downloads the scaffolds for single species that aren't represented in the complete genome dataset? likewise, and again, contigs and chromosome with priority to the highest assembly level. 

regards

**Comment by pirovc** [comment]
Hi,
Not sure if I got it right what you want but you can just omit the `-l` or use `-l all` to not filter by Assembly Level, allowing all categories to be used. `-j "species:1"` will then filter for the "best" assembly, based on [this priority list](https://github.com/pirovc/genome_updater#top-assemblies). Does that return what you need?
Best

**Comment by rjsorr** [comment]
Cheers @pirvoc 
My bad! that was what I exactly what I needed. Sometimes it helps to read the instructions properly :)

great program btw. The need to reduce databases to only what is necessary is a must considering the almost exponential growth. I'm looking forward to trying this with ganon. 

btw do you have a good suggestion for contamination removal based on relative distribution of reads in the negative controls (using ganon). I was looking at squeegee, recentrifuge or decontam, but maybe you have another? 

regards

**Comment by pirovc** [comment]
From those I think decontam is quite good for the task. you can also check out https://github.com/pirovc/grimer to visualize and maybe detect some contamination, decontam is integrated.
