### ISSUE TITLE
changing the parameters of an already downloaded database?

### ISSUE THREAD

**Issue by rjsorr** [pirovc/genome_updater#43]
Hi, I have downloaded the refseq bacterial complete genome database using the "P 1" option to just get a single assembly per species. However, I would also like a database with multiple strains per species, so the "P 0" option. However, as I have already downloaded using P 1 is it possilbe to somehow do an update or fix on this database using a P 0, so saving time by not downloading all the same files again... just those that are missing? 

regards

**Comment by pirovc** [comment]
Hi @rjsorr. Yes, you just have to run genome_updater with the desired parameters with the same output folder `-o` used in the first run. It will "update" the repository based on the new parameters and just download the missing files.

**Comment by rjsorr** [comment]
Hi @pirovc, I tried that but no luck! 

original download using older version:
genome_updater.sh -g "bacteria" -d "refseq" -l "Complete Genome" -f "genomic.fna.gz,assembly_report.txt" -o "bac_refseq_cg" -b "21_12_2021" -j "species:1" -a -m -u -r -p -t 12 &

new update: 
genome_updater.sh -d "refseq" -g "bacteria" -l "Complete Genome" -f "genomic.fna.gz" -o "bac_refseq_cg" P 0 -t 8 -u -m &

Log attached where I moved and ran it in a test folder. 
[2022-03-09_21-30-15.log](https://github.com/pirovc/genome_updater/files/8221583/2022-03-09_21-30-15.log)

**Comment by pirovc** [comment]
It should actually work between versions, no problems there. The log you sent does not match the command. Maybe you broke some of the links when you moved the folder? What's the output of `ls -lah bac_refseq_cg/*` ?

**Comment by rjsorr** [comment]
hi @pirovc, 

log file for the correct folder. same issue and  ls -lah bac_refseq_cg/ result 

ubuntu@regnesentralen:/media/ubuntu/Elements/reference_genomes/genome_updater$  ls -lah bac_refseq_cg/*
-rwxrwxrwx 1 ubuntu ubuntu 2,1M mars   9 20:33 bac_refseq_cg/assembly_summary.txt
-rwxrwxrwx 1 ubuntu ubuntu  28G mars   4 11:35 bac_refseq_cg/bac_cg.fa

bac_refseq_cg/2022-03-09_21-10-21:
total 4,6M
drwxrwxrwx 1 ubuntu ubuntu 4,0K mars   9 21:13 .
drwxrwxrwx 1 ubuntu ubuntu 2,4M mars  10 09:53 ..
drwxrwxrwx 1 ubuntu ubuntu 2,2M mars  10 09:48 files

bac_refseq_cg/2022-03-10_09-48-51:
total 12M
drwxrwxrwx 1 ubuntu ubuntu  400 mars  10 09:53 .
drwxrwxrwx 1 ubuntu ubuntu 2,4M mars  10 09:53 ..
-rwxrwxrwx 1 ubuntu ubuntu 1,3M mars  10 09:53 2022-03-10_09-48-51.log
-rwxrwxrwx 1 ubuntu ubuntu 7,7M mars  10 09:53 assembly_summary.txt
drwxrwxrwx 1 ubuntu ubuntu    0 mars  10 09:48 files

bac_refseq_cg/21_12_2021:
total 67M
drwxrwxrwx 1 ubuntu ubuntu 4,0K des.  24 19:32 .
drwxrwxrwx 1 ubuntu ubuntu 2,4M mars  10 09:53 ..
-rwxrwxrwx 1 ubuntu ubuntu 5,6K des.  24 19:32 2021-12-21_15-57-13.log
-rwxrwxrwx 1 ubuntu ubuntu 1,7M des.  24 19:32 2021-12-21_15-57-13_url_downloaded.txt
-rwxrwxrwx 1 ubuntu ubuntu 1,2K des.  24 19:32 2021-12-21_15-57-13_url_failed.txt
-rwxrwxrwx 1 ubuntu ubuntu 2,1M des.  21 15:57 assembly_summary.txt
drwxrwxrwx 1 ubuntu ubuntu 4,8M mars   9 21:02 files
-rwxrwxrwx 1 ubuntu ubuntu  55M des.  24 19:32 taxdump.tar.gz
-rwxrwxrwx 1 ubuntu ubuntu 677K mars   9 21:06 updated_assembly_accession.txt
-rwxrwxrwx 1 ubuntu ubuntu 688K des.  24 19:32 updated_sequence_accession.txt
[2022-03-10_09-48-51.log](https://github.com/pirovc/genome_updater/files/8221866/2022-03-10_09-48-51.log)

**Comment by pirovc** [comment]
The `assembly_summary.txt` in the main output folder (in your case `bac_refseq_cg/assembly_summary.txt`) should be an symbolic link to the latest `assembly_summary.txt` used inside one of the folders. That's how genome_updater keeps track of the versions. Not sure why but you have a file instead. To rollback and fix it, try:

```bash
cd bac_refseq_cg
rm assembly_summary.txt
ln -s 21_12_2021/assembly_summary.txt assembly_summary.txt
cd ..
genome_updater.sh -g "bacteria" -d "refseq" -l "Complete Genome" -f "genomic.fna.gz,assembly_report.txt" -o "bac_refseq_cg" -P 0 -m -u -r -p -t 12 &
```
