### ISSUE TITLE
update only linking to first version

### ISSUE THREAD

**Issue by rjsorr** [pirovc/genome_updater#44]
Hi, I am trying to add/update to a download, with 19k files needing to be downloaded, something that takes days. I am now experiencing a break in the download, something to do with our server. However, when I run the update again genome_updater is only updating to the first (original) version and ignoring the newer updates. how to overcome this issue, so I dont have to go back to the start each time? 
[2022-03-12_10-08-16.log](https://github.com/pirovc/genome_updater/files/8237369/2022-03-12_10-08-16.log)
[2022-03-11_00-03-25.log](https://github.com/pirovc/genome_updater/files/8237372/2022-03-11_00-03-25.log)

**Comment by pirovc** [comment]
This is the standard behavior now and there's not workaround it. I'll release a new version of genome_updater in the next days with new features and will include a fix for that too.

**Comment by pirovc** [comment]
It should be solved with v0.4.0, please give it a try

**Comment by rjsorr** [comment]
Not working for me unfortunately @pirovc. It is still just finding and linking to the first directory. 

  ubuntu@regnesentralen:/media/ubuntu/Elements/reference_genomes/genome_upd                                         ater$ genome_updater.sh -g "bacteria" -d "refseq" -l "Complete Genome" -f "genom                                         ic.fna.gz" -o "bac_refseq_cg" -P 0 -m -u -r -p -t 8 &
[1] 709006
(base) ubuntu@regnesentralen:/media/ubuntu/Elements/reference_genomes/genome_upd                                         ater$ -------------------------------------------
┌─┐┌─┐┌┐┌┌─┐┌┬┐┌─┐    ┬ ┬┌─┐┌┬┐┌─┐┌┬┐┌─┐┬─┐
│ ┬├┤ ││││ ││││├┤     │ │├─┘ ││├─┤ │ ├┤ ├┬┘
└─┘└─┘┘└┘└─┘┴ ┴└─┘────└─┘┴  ─┴┘┴ ┴ ┴ └─┘┴└─
                                     v0.4.0
-------------------------------------------
Mode: UPDATE - DOWNLOAD
Working directory: /media/ubuntu/Elements/reference_genomes/genome_updater/bac_r                                         efseq_cg/
-------------------------------------------
(base) ubuntu@regnesentralen:/media/ubuntu/Elements/reference_genomes/genome_updater$  - None

Checking for extra files in the current version [21_12_2021]
 - 6719 extra files
 - 0 files successfully deleted

Downloading assembly summary [2022-03-21_14-40-49]
 - Database [refseq]
 - Organism group [bacteria]
 - 242347 assembly entries available
 - 216449 assemblies removed based on filters:
   valid URLs
   version status=latest
   assembly level=Complete Genome
 - 25898 assembly entries to download

Updates available [21_12_2021 --> 2022-03-21_14-40-49]
 - 0 updated, 92 deleted, 19271 new entries

Linking versions [21_12_2021 --> 2022-03-21_14-40-49]
 - Done.

Setting-up new version [2022-03-21_14-40-49]
 - Done.

Updating
 - DELETE: Deleting 92 files
 - 92 files successfully deleted
 - NEW: Downloading 19271 files with 8 threads
jobs -r
[1]+  Running                 genome_updater.sh -g "bacteria" -d "refseq" -l "Complete Genome" -f "genomic.fna.gz" -o "bac_refseq_cg" -P 0 -m -u -r -p -t 8 &
(base) ubuntu@regnesentralen:/media/ubuntu/Elements/reference_genomes/genome_updater$ fg 1
genome_updater.sh -g "bacteria" -d "refseq" -l "Complete Genome" -f "genomic.fna.gz" -o "bac_refseq_cg" -P 0 -m -u -r -p -t 8
^Z
[1]+  Stopped                 genome_updater.sh -g "bacteria" -d "refseq" -l "Complete Genome" -f "genomic.fna.gz" -o "bac_refseq_cg" -P 0 -m -u -r -p -t 8
(base) ubuntu@regnesentralen:/media/ubuntu/Elements/reference_genomes/genome_updater$ ^C

**Comment by rjsorr** [comment]
Agree. Problem is I have another run from 03-21 in the same directory that it is not finding. It is only finding the first/original and just updating from this

**Comment by rjsorr** [comment]
Hi @pirovc, gave it a try but it is exiting without any errors. I guess the problem is in my command but I cannot see where? 

genome_updater.sh -g "bacteria" -d "refseq" -l "Complete Genome" -f "genomic.fna.gz" -o "bac_refseq_cg" -B "2022-03-12_10-08-16"  -P 0 -m -u -r -p -t 8 &

**Comment by pirovc** [comment]
If possible, can you show me the output of `ls -lah bac_refseq_cg/*` ?

**Comment by rjsorr** [comment]
bac_refseq_cg/assembly_summary.txt -> 2022-03-21_14-40-49/assemb                                              ly_summary.txt
-rwxrwxrwx 1 ubuntu ubuntu  28G mars   4 11:35 bac_refseq_cg/bac_cg.fa
-rwxrwxrwx 1 ubuntu ubuntu 9,1K mars  21 14:42 bac_refseq_cg/delete.tmp
-rwxrwxrwx 1 ubuntu ubuntu  157 mars  21 14:43 bac_refseq_cg/history.tsv
-rwxrwxrwx 1 ubuntu ubuntu  98K mars  21 14:44 bac_refseq_cg/missing.tmp
-rwxrwxrwx 1 ubuntu ubuntu 1,9M mars  21 14:42 bac_refseq_cg/new.tmp
-rwxrwxrwx 1 ubuntu ubuntu    0 mars  21 14:42 bac_refseq_cg/update.tmp
-rwxrwxrwx 1 ubuntu ubuntu 2,4M mars  21 14:43 bac_refseq_cg/url_list_download.tmp
-rwxrwxrwx 1 ubuntu ubuntu 1,8M mars  21 14:43 bac_refseq_cg/url_success_download.tmp

bac_refseq_cg/2022-03-12_10-08-16:
total 19M
drwxrwxrwx 1 ubuntu ubuntu 4,0K mars  12 10:09 .
drwxrwxrwx 1 ubuntu ubuntu 2,4M mars  21 19:51 ..
-rwxrwxrwx 1 ubuntu ubuntu 421K mars  16 22:47 2022-03-12_10-08-16.log
-rwxrwxrwx 1 ubuntu ubuntu 7,7M mars  12 10:09 assembly_summary.txt
drwxrwxrwx 1 ubuntu ubuntu 7,7M mars  16 22:47 files
-rwxrwxrwx 1 ubuntu ubuntu 9,4K mars  12 10:09 updated_assembly_accession.txt

bac_refseq_cg/2022-03-21_14-40-49:
total 4,8M
drwxrwxrwx 1 ubuntu ubuntu 4,0K mars  21 19:51 .
drwxrwxrwx 1 ubuntu ubuntu 2,4M mars  21 19:51 ..
-rwxrwxrwx 1 ubuntu ubuntu 1,6K mars  21 19:51 2022-03-21_14-40-49.log
drwxrwxrwx 1 ubuntu ubuntu 2,4M mars  21 19:51 files

bac_refseq_cg/2022-03-21_14-44-29:
total 2,4M
drwxrwxrwx 1 ubuntu ubuntu    0 mars  21 14:44 .
drwxrwxrwx 1 ubuntu ubuntu 2,4M mars  21 19:51 ..
-rwxrwxrwx 1 ubuntu ubuntu 1022 mars  21 14:44 2022-03-21_14-44-29.log
drwxrwxrwx 1 ubuntu ubuntu    0 mars  21 14:44 files

bac_refseq_cg/21_12_2021:
total 67M
drwxrwxrwx 1 ubuntu ubuntu 4,0K mars  10 10:44 .
drwxrwxrwx 1 ubuntu ubuntu 2,4M mars  21 19:51 ..
-rwxrwxrwx 1 ubuntu ubuntu 5,6K des.  24 19:32 2021-12-21_15-57-13.log
-rwxrwxrwx 1 ubuntu ubuntu 1,7M des.  24 19:32 2021-12-21_15-57-13_url_downloaded.txt
-rwxrwxrwx 1 ubuntu ubuntu 1,2K des.  24 19:32 2021-12-21_15-57-13_url_failed.txt
-rwxrwxrwx 1 ubuntu ubuntu  665 mars  10 10:44 2022-03-10_10-38-43_url_downloaded.txt
-rwxrwxrwx 1 ubuntu ubuntu    0 mars  10 10:44 2022-03-10_10-38-43_url_failed.txt
-rwxrwxrwx 1 ubuntu ubuntu 2,1M des.  21 15:57 assembly_summary.txt
drwxrwxrwx 1 ubuntu ubuntu 4,8M mars  10 10:40 files
-rwxrwxrwx 1 ubuntu ubuntu  55M des.  24 19:32 taxdump.tar.gz
-rwxrwxrwx 1 ubuntu ubuntu 677K mars  10 10:44 updated_assembly_accession.txt
-rwxrwxrwx 1 ubuntu ubuntu 689K mars  10 10:47 updated_sequence_accession.txt

**Comment by pirovc** [comment]
I didn't manage to recreate the bug and can't see a problem with your command or files. Does it print something before it fails? no files or log generated?

**Comment by rjsorr** [comment]
worked :)
