### ISSUE TITLE
Option to filter at higher taxonomic levels

### ISSUE THREAD

**Issue by rjsorr** [pirovc/genome_updater#46]
Hi @pirovc, I'm wondering as to the possibilty as adding a filter at higher taxonomic levels than just species? I want to make a compact eukaryote database and it would be great for example to choose one represenatative genome per phylum, class or order. For me as I work on bacteria, classifying eukaryotes to species is not important. However, classifying to higher levels would really help gauge an overview of what is represented in the sampling. regards

**Comment by pirovc** [comment]
Hi @rjsorr. It's actually a very good idea, will add to the feature list, thanks!

**Comment by pirovc** [comment]
Thanks again for the suggestion, you can now do that with v0.5.0. For example, get 2 assemblies for each bacterial genus in refseq:

`./genome_updater.sh -d "refseq" -g "bacteria" -f "genomic.fna.gz" -A "genus:1" -t 12 -m -o rs_genus_top2 `
