### ISSUE TITLE
Update static GTDB urls in script

### ISSUE THREAD

**Issue by aistBMRG** [pirovc/genome_updater#47]
Thanks for developing this tool; it is very helpful.

It seems that GTDB just updated to release207.

For the Archaea it seems that the summary files is now "ar53_taxonomy_r207.tsv.gz"; so that is different from the file in your script, which points to "ar122_taxonomy.tsv.gz"

FYI.

Dieter

**Comment by pirovc** [comment]
I'm glad the tool is useful for you and thanks for the heads up, I'll provide a quick fix shortly!

**Comment by pirovc** [comment]
GTDB links to release 07-RS207 fixed in v0.4.1
