### ISSUE TITLE
Script is not working on a 2022 MacBook Pro M1 Pro 

### ISSUE THREAD

**Issue by ltalignani** [pirovc/genome_updater#72]
Hello all,

When I try the following command:

`./genome_updater.sh -d "refseq" -g "viral" -c "all" -f "genomic.fna.gz" -o "all_virus_genomes" -t 10`

bash return this error message:

`./genome_updater.sh: line 905: declare: -A: invalid option 
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]`

I have installed the script with wget, then I tried conda install also. 

Any idea of what goes wrong ?

Regards

**Comment by pirovc** [comment]
Hi @ltalignani, unfortunately I do not have access to a MacOs to try it but it seems like you are using an old version of bash. This command is only compatible with bash v4 or higher https://rotadev.com/associative-arrays-error-declare-a-invalid-option-dev/

**Comment by pirovc** [comment]
thanks for the links. Currently zsh and MacOs are not directly supported and the bash>=4 is a requirement.

Plans to increase compatibility with older bash or direct support to MacOs installs are not planned. However, if the bash tools are there in the right versions, it usually works. It's really hard to keep a solid and broad compatibility with so many systems without a proper version control (usually the case with bash and shell utilities).

If you can't get to update bash you could try to use an older versions (v0.4.1 for example) where declare was not used.
