### ISSUE TITLE
questions on keep full taxonomy of downloaded genomes

### ISSUE THREAD

**Issue by jianshu93** [pirovc/genome_updater#79]
Hello Team,

This is really a fast genome download. I can download all refseq+genebank assembly in less than 6 hours using 64 threads:
genome_updater.sh -d "refseq,genbank" -g "archaea,bacteria" -f "genomic.fna.gz" -o "GTDB_complete" -M "gtdb" -t 64 -m

 However, only species name is there in the assembly_summary.txt

Is there a way to have full taxonomies? e.g. phylum and class and family level.

Thanks,

Jianshu

**Comment by pirovc** [comment]
the assembly_summary.txt is provided by NCBI and provides only taxid and species taxid in the cols. 6 and 7, respectively. Check out https://ftp.ncbi.nlm.nih.gov/genomes/README_assembly_summary.txt). To get the full lineage you'll have to parse the taxonomy files manually https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/ or use some library like [multitax](https://github.com/pirovc/multitax) or [taxonkit](https://github.com/shenwei356/taxonkit)
