### ISSUE TITLE
download issues

### ISSUE THREAD

**Issue by rjsorr** [pirovc/genome_updater#91]
Failed to download ftp://ftp.ncbi.nlm.nih.gov/genomes/refseq/assembly_summary_refseq.txt

**Comment by pirovc** [comment]
Can you be more specific?

**Comment by rjsorr** [comment]
Not really. It is not downloading the assemblies. It retries 3x then fails. Will try again later and send you the full log. But the problem may simply be the FTP connection

Get BlueMail for Android<https://bluemail.me>
On 16 Nov 2023, at 13:48, pirovc ***@***.******@***.***>> wrote:

Can you be more specific?

**Comment by rjsorr** [comment]
conda activate genome_updater
##genome_updater.sh -d "refseq,genbank" -T "1386" -l "complete genome" -f "genomic.fna.gz" -o "bacillus23all" -t 12 -m &
genome_updater.sh -d "genbank" -T "1386" -l "complete genome" -f "genomic.fna.gz" -o "bacillus23all" -t 12 -m &


[2] 125063
(genome_updater) ubuntu@workstation:/media/ubuntu/Pandora/REFBIO2023$ -------------------------------------------
┌─┐┌─┐┌┐┌┌─┐┌┬┐┌─┐    ┬ ┬┌─┐┌┬┐┌─┐┌┬┐┌─┐┬─┐
│ ┬├┤ ││││ ││││├┤     │ │├─┘ ││├─┤ │ ├┤ ├┬┘
└─┘└─┘┘└┘└─┘┴ ┴└─┘────└─┘┴  ─┴┘┴ ┴ ┴ └─┘┴└─
                                     v0.6.3
-------------------------------------------
Mode: NEW
Args: -T '1386' -t '12' -o 'bacillus23all' -l 'complete genome' -f 'genomic.fna.gz' -d 'genbank' -m
Outp: /media/ubuntu/Pandora/REFBIO2023/bacillus23all/
-------------------------------------
Downloading assembly summary [2023-11-16_15-01-42]
 - Database [genbank]
 - Failed to download ftp://ftp.ncbi.nlm.nih.gov/genomes/genbank/assembly_summary_genbank.txt. Trying again #2

**Comment by pirovc** [comment]
so you could be more specific after all. It does not seem to be a problem with genome_updater or from NCBI side. Your command works just fine for me. 

You could try some of the following: https://github.com/pirovc/genome_updater/issues/88#issuecomment-1655723023
