### ISSUE TITLE
citation?

### ISSUE THREAD

**Issue by rjsorr** [pirovc/genome_updater#92]
How we citing genome_updater?

**Comment by pirovc** [comment]
You can use this repository url directly (https://github.com/pirovc/genome_updater) or cite the zenodo entry:

C. Piro, V. (2023). pirovc/genome_updater: genome_updater v0.6.3 (v0.6.3). Zenodo. https://doi.org/10.5281/zenodo.8108640

**Comment by mbhall88** [comment]
@pirovc I love this tool. You should consider doing a [JOSS paper](https://joss.theoj.org/) so we can all give it a good article citation.

**Comment by pirovc** [comment]
A [citation file](https://github.com/pirovc/genome_updater/blob/master/CITATION.cff) was added to the repository to facilitate citing the software:

![image](https://github.com/pirovc/genome_updater/assets/4673375/233b406a-0bff-4182-a07f-c9cfa45fd5c4)
