### ISSUE TITLE
Species representative selection criteria

### ISSUE THREAD

**Issue by JensUweUlrich** [pirovc/genome_updater#93]
Hi Vitor

I have a question regarding the selection of species representatives from GenBank. When I use the following command
`genome_updater.sh -d refseq -g archaea,bacteria,fungi,viral -l complete genome,chromosome, -f genomic.fna.gz -o refseq-abfv -t 12 -A species:1 -m -a -p`
what is the criteria of choosing a representative genome for each of the species?

Thanks
Jens

**Comment by pirovc** [comment]
Hi Jens, the criteria is described [here](https://github.com/pirovc/genome_updater?tab=readme-ov-file#top-assemblies). I sort the candidates based on 4 categories, based on an order of importance. After the sorting, I take the top of the list (in your case only the first).
