### ISSUE TITLE
Can genome_updater's logic be applied to SRA data updates?

### ISSUE THREAD

**Issue by Dx-wmc** [pirovc/genome_updater#97]
Hi, I noticed that genome_updater is an excellent tool for downloading and updating NCBI GenBank data without re-downloading everything. Since SRA data is also constantly updated, is it possible to apply a similar download logic to SRA data as well? Or if there is any tool that has already implemented this functionality? This could be very useful for keeping SRA datasets up-to-date efficiently. Thank you!

**Comment by pirovc** [comment]
Thanks for the commentary. 

I'm not very familiarized with the SRA database storage methods, but as far as I'm concerned, there's no way to apply genome_updater to it in any easy way.

I'm not aware of a similar tools to download SRA entries besides the ones provided by NCBI directly. Hope you find something suitable.
